version: '3'

services:
    database:
        container_name: Postgres_db
        image: postgres
        env_file:
            - environment.env
        ports:
            - 5432:5432

    web_service:
        container_name: Django_web_app
        build: .
        command: bash -c "while !</dev/tcp/database/5432; do sleep 1; done;python manage.py runserver 0.0.0.0:8000"
        volumes:
            - .:/src
        env_file:
            - environment.env
        ports:
            - "8000:8000"
        links:
            - database
        depends_on:
            - database
