# Generated by Django 3.0.3 on 2020-03-01 03:15

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_cashback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cashback_applied',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='cashback_value',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='BRL', max_digits=14, null=True),
        ),
    ]
