# Generated by Django 3.0.3 on 2020-03-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer_cashback', '0002_auto_20200301_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cashback_applied',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
